







	



.build/uno/LiquidCrystal595/LiquidCrystal595.d : /usr/share/arduino/libraries/LiquidCrystal595/LiquidCrystal595.cpp
	@mkdir -p .build/uno/LiquidCrystal595
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/LiquidCrystal595 -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/LiquidCrystal595 -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/uno/LiquidCrystal595/LiquidCrystal595.d .build/uno/LiquidCrystal595/" | cat - $@ > $@~ && mv $@~ $@



.build/uno/LiquidCrystal595/dependencies.d : .build/uno/LiquidCrystal595/LiquidCrystal595.d
	@echo [96mScanning dependencies of LiquidCrystal595[0m
	@mkdir -p .build/uno/LiquidCrystal595
	@cat $^ > $@;

all : .build/uno/LiquidCrystal595/dependencies.d
	@true

